### PR TITLE
Fixup S60P bootloader size

### PR DESCRIPTION
**Pull request by Ralim**
Fix S60P bootloader size to match factory one 😢  my bad.

### CODE REVIEW

**Comment by discip** [comment]
@Ralim
I'm not absolutely sure, but it seems you mixed something up here, as you actually changed the **`TS80P`** settings and not the parameters for the **`S60P`**.

Since the changes were for the **`TS80P`** I flashed the changed file to the according and bricked it.

Will see if I'll be able to get it back to life with the ST-link.

The flashed bootloader is still horizontally flipped, also the runtime.dfu is flipped the same way.

**Comment by discip** [comment]
@Ralim
I'm not absolutely sure, but it seems you mixed something up here, as you actually changed the **`TS80P`** settings and not the parameters for the **`S60P`**.

Since the changes were for the **`TS80P`** I flashed the changed file to the accordingd device and bricked it.

Will see if I'll be able to get it back to life with the ST-link.

The flashed bootloader is still horizontally flipped, also the runtime.dfu is flipped the same way.

**Comment by discip** [comment]
@Ralim
I'm not absolutely sure, but it seems you mixed something up here, as you actually changed the **`TS80P`** settings and not the parameters for the **`S60P`**.

Since the changes were for the **`TS80P`** I flashed the changed file to the according device and bricked it.

Will see if I'll be able to get it back to life with the ST-link.

The flashed bootloader is still horizontally flipped, also the runtime.dfu is flipped the same way.

**Comment by Ralim** [comment]
Arrg, apologies, shouldn't have done this late at night.

**Comment by discip** [comment]
No worries. 
I think this is fixable. 😊

**Comment by Ralim** [comment]
yeah easily fixable to re-flash via SWD over the usb port, just my dumb mistake

**Pull request closed without merging**
