### PR TITLE
Drop OLED flip for TS80P

### LINKED ISSUE #23: TS80/P horizontally flipped bootloader screen
After the latest release unfortunately the screen on both the **`TS80`** & **`TS80P`** is horizontally flipped.
The logo as well as the text.

### PR DESCRIPTION
**Pull request by Ralim**
fixes #23

### CODE REVIEW

**Comment by discip** [comment]
Not able to test as my ST-Link isn't detected anymore.

Will report back as soon as the **`TS80P`** is alive again.

**Comment by discip** [comment]
This is not going to fix the problem as this PR only affects the **`TS80`**.

I tried it with the corresponding line removed for the **`TS80P`**, but that only made the text readable for lefties.


The current issue is that all content shown on the OLED display is mirrored along the vertical center of the screen, so to read the text you need to read the letters from right to left, while each letter is reversed.
(Or you could hold the iron with the usb side to a mirror and read it in there.)

I think the issue is the removal of these lines that you deleted in commit https://github.com/Ralim/IronOS-dfu/commit/628fc9858ab291ed994d99e2181919561e2e6092:

``` C
#ifdef OLED_FLIP
    0x80, 0xA1, /*Set Segment remap to backwards*/
#else
    0x80, 0xA0, /*Set Segment remap to normal*/
#endif
```
Just a guess though. 😊

**Comment by discip** [comment]
@Ralim
This is not going to fix the problem as this PR only affects the **`TS80`**.

I tried it with the corresponding line removed for the **`TS80P`**, but that only made the text readable for lefties.


The current issue is that all content shown on the OLED display is mirrored along the vertical center of the screen, so to read the text you need to read the letters from right to left, while each letter is reversed.
(Or you could hold the iron with the usb side to a mirror and read it in there.)

I think the issue is the removal of these lines that you deleted in commit https://github.com/Ralim/IronOS-dfu/commit/628fc9858ab291ed994d99e2181919561e2e6092:

``` C
#ifdef OLED_FLIP
    0x80, 0xA1, /*Set Segment remap to backwards*/
#else
    0x80, 0xA0, /*Set Segment remap to normal*/
#endif
```
Just a guess though. 😊

**Comment by Ralim** [comment]
Hmm, those lines were pulled to the header and _should_ be the same.
Will need to test this though

**Comment by discip** [comment]
@Ralim
Have you, by any chance, had time to look into this yet?

**Comment by discip** [comment]
@Ralim
Have you by any chance had time to look into this?

**Comment by discip** [comment]
@Ralim
Hope you have some time to sort this out.
Just so we are on the same page, that's what I'm seeing:

flipped_screen

thanks in advance

**Comment by discip** [comment]
@Ralim
Now it's in leftie mode. (readable but upside down)  🤣

**Comment by discip** [comment]
@Ralim
Now it's in leftie mode. (readable but upside down)  🤣

**Comment by discip** [comment]
@Ralim
ping 😊

**Comment by Ralim** [comment]
@discip 
Pong 🤣 
Works for me here

**Comment by discip** [comment]
# Thank you so much! 👍
### It finally works!

**Review by discip — APPROVED** [review]

**Pull request merged**
