### PR TITLE
Fix S60P flash size

### PR DESCRIPTION
**Pull request by Ralim**

### CODE REVIEW

**Comment by Ralim** [comment]
Okay, @discip  should be fixed. Found a few bugs 😓

**Comment by Ralim** [comment]
If you are able to open the unit you could flash directly over swd as best bet if that is ok by you. if not LMK and ill help

**Comment by Ralim** [comment]
Also, at some point (no pressure lol) I should make a higher res ironos logo for this 🤣

**Comment by discip** [comment]
## It finally works! 👍
Even the bootlogo!
* btw: I used the bootlogo which is intended for the **`S60`**, maybe you could rename the output file accordingly. 
Something like: **`S60/P`**.

But there are still scrambled pixels left and right beside the logo & also beside the text.

**Comment by Ralim** [comment]
>But there are still scrambled pixels left and right beside the logo & also beside the text.

This code doesnt handle the larger screen overly well. Do need to fix that up

**Comment by Ralim** [comment]
>This code doesnt handle the larger screen overly well. Do need to fix that up

Fixed

**Comment by Ralim** [comment]
>btw: I used the bootlogo which is intended for the S60, maybe you could rename the output file accordingly.

Updated the name and tagged new release

**Comment by discip** [comment]
As always will test later. 😊

**Comment by discip** [comment]
## Absolutely flawless!

**Review by discip — APPROVED** [review]
For the **`S60P`** everything works as expected!

**Pull request merged**
