### PR TITLE
Actually build MHP30 runtime at 0x8000, fix #15

### LINKED ISSUE #15: Could not install the runtime DFU on MHP30
Hello,

I successfully installed your DFU bootloader on 3 TS100, then I bricked my TS80P :sweat_smile: (flash was locked, now fixed with a st-link) but I've an issue with the MHP30: original bootloader (2.2B) refuses to install the RUNTIME.HEX, it always returns RUNTIME.NOT (and RUNTIME.ERR if I try directly again). Tested on a Windows.
While flashing the latest MHP30_EN.HEX works fine...

Any idea ?

*Edit*: I just saw that the same issue was mentioned in [this comment](https://github.com/Ralim/IronOS-dfu/issues/2#issuecomment-1153963295)

### PR DESCRIPTION
**Pull request by ElementW**

### CODE REVIEW

**Comment by damex** [comment]
how is it expected to be flashed ? any extra modification/adjustment needed?

i have current release of IronOS-DFU and just tried building and flashing this release.

```
dfu-util.exe -D bootloader.dfu
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 0483
Match product ID from file: df11
Multiple alternate interfaces for DfuSe file
Opening DFU capable USB device...
Device ID 28e9:0189
Device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Interface #0 ...
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 011a
Device returned transfer size 1024
DfuSe interface name: "Internal Flash "
File contains 1 DFU images
Parsing DFU image 1
Target name: ST...
Image for alternate setting 0, (1 elements, total size = 5336)
Setting Alternate Interface #0 ...
Parsing element 1, address = 0x08000000, size = 5328
Last page at 0x080014cf is not writeable

dfu-util.exe -D runtime.dfu
dfu-util 0.11

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2021 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Match vendor ID from file: 0483
Match product ID from file: df11
Multiple alternate interfaces for DfuSe file
Opening DFU capable USB device...
Device ID 28e9:0189
Device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Interface #0 ...
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 011a
Device returned transfer size 1024
DfuSe interface name: "Internal Flash "
File contains 1 DFU images
Parsing DFU image 1
Target name: ST...
Image for alternate setting 0, (1 elements, total size = 5336)
Setting Alternate Interface #0 ...
Parsing element 1, address = 0x08004400, size = 5328
Last page at 0x080058cf is not writeable
```

**Comment by damex** [comment]
it can actually be written through stlink/swd but then device does always boot in to dfu with internal flash exposed and can not flash current release of ironos with same error as above about region not being writeable.

flashing old bootloader 'as is' through stlink/swd does not fix it either.

i can restore old full flash and then it works again - bootloader boots without screen active and last ironos firmware could be flashed as usual

**Review by Ralim — APPROVED** [review]

**Comment by corndog2000** [comment]
Bump to get pull request approved.

**Comment by ElementW** [comment]
Rebasing turns this into a no-op, because [it was added in `c157229`](https://github.com/Ralim/IronOS-dfu/commit/c157229e1e8fb465a8abebd13ad7c7489885f7c9#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R25).
Closing.

**Pull request closed without merging**
